version: '3.8'

services:
 
  backend:
    build: ./server
    container_name: note-backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
  frontend:
    build: 
      context: ./client
      args:
        - VITE_API_URL=http://13.62.46.194:3000/api
    container_name: note-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
